theme: jekyll-theme-architect
title: Data Science Projects Blog
description: The site focuses on breaking down different data science projects repositories to something that can be easily read and understood. The projects range from Machine Learning, Visualizations, NLP to feature engineering and so much more.
